// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY40bH0JbJ1f_b94EuCh4EI6XCWmU3z4I',
    appId: '1:309600422747:web:d3619aa78298926e93687e',
    messagingSenderId: '309600422747',
    projectId: 'easytrack-41741',
    authDomain: 'easytrack-41741.firebaseapp.com',
    storageBucket: 'easytrack-41741.firebasestorage.app',
    measurementId: 'G-1K7W8CRSYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6FGzcj6P4621enFtFRqBDemI0O8a2-g',
    appId: '1:309600422747:android:63a9544c6ebd621a93687e',
    messagingSenderId: '309600422747',
    projectId: 'easytrack-41741',
    storageBucket: 'easytrack-41741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa2LZeJcjAyS4LfTkvtLnWZTVe8RnHo_E',
    appId: '1:309600422747:ios:7adbe21a19d83f1593687e',
    messagingSenderId: '309600422747',
    projectId: 'easytrack-41741',
    storageBucket: 'easytrack-41741.firebasestorage.app',
    iosBundleId: 'com.KHEasyDev.easyTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY40bH0JbJ1f_b94EuCh4EI6XCWmU3z4I',
    appId: '1:309600422747:web:caf9c3ec9faa0e1a93687e',
    messagingSenderId: '309600422747',
    projectId: 'easytrack-41741',
    authDomain: 'easytrack-41741.firebaseapp.com',
    storageBucket: 'easytrack-41741.firebasestorage.app',
    measurementId: 'G-3TYYBTB77W',
  );
}
