// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRfkkt5813tTy4oTrYEAqXOWg7OPuCIE',
    appId: '1:388015310398:web:9275b58bf123867ba3b36f',
    messagingSenderId: '388015310398',
    projectId: 'easybirthday-67eec',
    authDomain: 'easybirthday-67eec.firebaseapp.com',
    storageBucket: 'easybirthday-67eec.appspot.com',
    measurementId: 'G-ES89YMK7W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ50WCVabvU5r0PBaBgumTbTfrZlCbqvc',
    appId: '1:388015310398:android:c97876e8c9b5b998a3b36f',
    messagingSenderId: '388015310398',
    projectId: 'easybirthday-67eec',
    storageBucket: 'easybirthday-67eec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-H0s2q4l8DEaALynYlvu4fDD7sbwKHE',
    appId: '1:388015310398:ios:3fd3313da6c7d098a3b36f',
    messagingSenderId: '388015310398',
    projectId: 'easybirthday-67eec',
    storageBucket: 'easybirthday-67eec.appspot.com',
    iosBundleId: 'com.KHEasyDev.easyBirthday',
  );
}
